name: Manage Releases

on:
  push:
    branches:
      - main

jobs:
  versioning-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-Increment Version
        id: version
        run: |
          # Extract the current version from hacs.json
          CURRENT_VERSION=$(jq -r '.version // empty' hacs.json)
          echo "Current Version: $CURRENT_VERSION"

          # If no version is found, start at 1.0.0
          if [[ -z "$CURRENT_VERSION" || "$CURRENT_VERSION" == "null" ]]; then
            CURRENT_VERSION="1.0.0"
          fi

          # Increment the patch version
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
          if [[ -z "$PATCH" ]]; then
            echo "Error: Could not parse version from hacs.json."
            exit 1
          fi
          NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
          echo "New Version: $NEW_VERSION"

          # Export the new version for later steps
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Debug Version
        run: echo "New Version:$NEW_VERSION"
        env:
          NEW_VERSION: ${{ env.new_version }}

      - name: Update hacs.json and manifest.json
        run: |
          # Update hacs.json and manifest.json with the new version
          jq ".version = \"${{ env.new_version }}\"" hacs.json > tmp_hacs.json && mv tmp_hacs.json hacs.json
          jq ".version = \"${{ env.new_version }}\"" manifest.json > tmp_manifest.json && mv tmp_manifest.json manifest.json

          # Stage changes for commit
          git add hacs.json manifest.json

          # Commit the version bump
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git commit -m "Auto-bump version to v${{ env.new_version }}" || echo "No changes to commit"
